/* XPM */
char *pacman[] = {
/* columns rows colors chars-per-pixel */
"192 112 64 1 ",
"  c #010101",
". c #160602",
"X c #01011B",
"o c #101612",
"O c #2B1107",
"+ c #04052D",
"@ c #2B292D",
"# c #1C2922",
"$ c #730D05",
"% c #522F07",
"& c #56211A",
"* c #714F06",
"= c #604C16",
"- c #00107D",
"; c #000E75",
": c #2D2D5B",
"> c #493675",
", c #044E53",
"< c #076B6C",
"1 c #28555D",
"2 c #5F5C60",
"3 c #8B0101",
"4 c #940F0C",
"5 c #AF110A",
"6 c #A0321C",
"7 c #CA1C11",
"8 c #99660C",
"9 c #D65315",
"0 c #A1635F",
"q c #D45751",
"w c #F66969",
"e c #D26763",
"r c #BB9500",
"t c #AB8704",
"y c #E2A518",
"u c #F9CF22",
"i c #DBB06B",
"p c #001389",
"a c #1122AC",
"s c #4A3B8D",
"d c #7D53A8",
"f c #625897",
"g c #002EDB",
"h c #0034E8",
"j c #1228CA",
"k c #204BDF",
"l c #2F67AD",
"z c #895DB2",
"x c #9A78C2",
"c c #038F8F",
"v c #15A9AD",
"b c #69AAD2",
"n c #4FABB2",
"m c #A099A4",
"M c #F58A8B",
"N c #EAB0AE",
"B c #F7D9A7",
"V c #B3B0CF",
"C c #9E9ECF",
"Z c #F8CDCD",
"A c #F6F7F7",
"S c #D7D9DE",
"D c #B4C7D5",
"F c #778478",
/* pixels */
"     .&&&&.          .&&&&.X         O8888.          O8888O          O0002O          O0002O          o,111o          o1111o          o>2f>X          o>22>X                                     ",
"   o2eq664$&       o2eq6653O.      o2iuyy96$.      o2iuy996%.      o2NNMMwq6.      o2NZNMwq&o      .2bbvvc<#       o2bbvvc<#       o2VVxzf>:X      o2VVxzf>:        .%***%o          %*==%.     ",
"   0ZN743333$     .0SM734333$     omABy999993      mABy999994.    .0ZZNMwwww6     .0ZZMwwwww6o     mSDncc<<<,     omSDnvc<<<,     .mASxzzsss:     .mASxzdsss:.     Otyyrrrt%       %tyyrrr8%    ",
"  &MZw743443$.   XOMZM534444$.    =BABy999997O    %BABy999997O    2ZZNMMMwwwe&   X=ZZNMMwwwwq&    ,VSbvcccc<,o    ,CSbvcccc<,o    @SAVzzzfsss#    :SAVzzzsfss+    %yiiyy**rt=     %yBuuy8*rt=   ",
"  4wNZN66VS0$&    4wNZN66NS0$%   .tBBAB99BZi73   oriBAB99BZe73    mZZAZMMZZMe6X  omZAAZMMZZNe6   ocCSSDvnDSn<,    cbSADvvDSb<,    fVSAVzzVSms:    fDSAVzzSSms:    tiABuyOorr8O    8BAZuyOotrtO  ",
" .5wAm20eA2z$%.  .7eAV200A20&&   oyuAm2eiS2F74.  ouiAmFeMSFm74.  oNZAm2MZS2me9.  oNZAm2MNS20e9.  #vbAC2nbS2F<,   ovbAV2nbS2F<,   XzVAV2zVS2zf>X  .zVAmfxVSfzf>X  %yiABuy8*rrr*   OyiZBuyt*rt*o  ",
" .5eZf@2eD@2&%   .5eS2@0eD#2$&.  oyuA2@0MD@275.  ouuA2#0iD#274.  ONZA2@eZD#2e9.  oNZA2#eZD@2e6.  ovbA2#cbD@1<,o  ovbS2@cDD@1<,   .zVA2#dVV@2s>X  odVA2#dVD@1ss.  *yuuuuyrrrrr*.  *yuuuyyt*=oo   ",
" .7qmSm&=SD0$&.  .5qmSm=2SDz$%   ouuDSm0qSD074.  OyuDSm80SV074.  oNZVSmmeSDfqq.  oNZVSmzMDVmeq.  ovbCSmnnSVF<,   ovbCSmvnSDF<,   .zCVSmdzSVzss   .dCVSmdzSVFs>X  *ryyy88*****%   *yyyyt*o       ",
" .5q=2&$$&2&$%.  .5q=2&$$&2O$%   ouu82=96=2$74.  Ouu82=96=2$75.  oNZ022ee22=q9.  oNZ022qq22=q9.  ovb<21cc12@,,  o#vb121c<12,,,   .dC22:df:2:ssX  ozC22:d>&2:s>X  *rrrrtttttt**o  =rrrrrt*O      ",
" .5q6$333$O$3&   .5q5$$33$$$$%.  oyuy899966674.  oyuy899966975.  oNZM0qwwq6qqq.  oNZM0ewwq6qqq.  ovbvcccc<,,<,o  ,vbv<ccc,,<<,   XdVx>sdd>:ss>   XzVxsszd>:ss>X  %rrrrrrrrrt**   %rrrrrrrr8%O   ",
" .5q75533333$%   .7q755333333&   ouuuyy9999975.  oyuuyy9999673.  @NZNwMMwwwwqq.  #NZNwMMwwwweq. X#vbvvvccc<<<,   ovbvvvcc<<<<,o  ozVCzzzdssss>.  XdVxzzzzsssssX  o8rrrrrrrt8*%   .8rrrrrrrt8*O  ",
" .7q75533333$%.  .5q65533333$%   oyuyyy9999773.  ouuuyy9999975.  #NZNMMMwwwwq9.  #NZNMMMwwwwq9.  #vbvvvvcc<<<,o  ovbvvvvcc<<<,   .zVxzzzzssss>X  .dVxzzzzssss>    %trrrrrt***o    %trrrrrt8**.  ",
" .5q6553333$$%.  .5q755$$333$%.  oyuyyy9999974.  oyuuyy6699973.  ONZNMMMwwwqqq   oNZMMM00wwwq6o  ovbvvvccc<<<,   ovbvvvc<c<<<,   XzVzdzzdss>s>   XdVCzzs>ssss>X    =trrt88**.      =trrt8***O   ",
" .56OO5333O.$&    Oq75$  $33$O   OytO%y999$.34.   =yuy8..6995O   #Nm@&eMwq&O6q.   2NNM0..6wwq&   ovno,ccc<#o,,o   ,nvvco <<<,o   odf+@dzds+X:>X   @Vxz>o.:sss+      O%****O.        O%***=O.    ",
" .$.  O33O   O     &5$    $$O    o8O  %99%  .$.    =y8.  .66O    #0#  &Mw&  .*.    2M0o  .6q&    o<o  ,cc#   #     1v<o   ,<#    .>o  @zd@  X:X    :z>. .X:s@          .              ..o.      ",
"       OO           O.    ..      .    OO           O.    .O     XX  XX&@X         .@O   Xo&      X    #o           #o    oo      .    +@           @.    .+                                    ",
"    XO&&&&.          O&&&&.X         O88**.          O*8**.          .2202O.         o200=O.X        o1111o          o111@o          o>>2>X          O>22>X                                     ",
"   o2eq644$O       o2eq6643O.      #2iuyy96$.      o0iuy999%.      O0NZMMwq&.      o0NZMMwq&.      o2nbvcc<,       o2nbvvc<#       o2VVxzfs@.      o2CVxzf>@X        %***%o          %**=%o     ",
"  .zZM743333$     .0SM734333$     omABu999993     .mABu999973     .mZZMMwwww6     .0ZZMMwwww6X     mSDvcc<<<,      mADvvc<<<,     .mASxzzsss:     .mASxzdsss:      Otyyrrr8%.      Otyyrrr8%    ",
"  OMZM533443$.   XOMSw634444$.    =BAiy999997O    %BABy999997O    @ZZNMMwwwwe&    :ZZNMMwwwwe&    ,DSCvvccc<,o    ,CSbvcccc<,o    @SAVzzzfsss+    :SAVzzzsfss+    %yiiuyrrrt=     %yiiuyrrrt=   ",
"  4wNZN66NS0$%    4wNZN66NZ0$%    tiBAB99BZM7$   .tiBABq9BZM73   omZZAZMMZZMe6   .mZZABMMZZNe6    cCSSDvvDSm<,    vbSADvvDSn<,    fVSAZzzVSCs:    fVAADzzVSxs:   .8BAAuyrrrrtO   .tiAAuyrrrrtO  ",
" .5eAAAeeAAS4%   .7eAAAe0AAZ&&.  ouiAAAMiAAZ75.  ouuAAAiiAAZ75.  ONZAAANNAAAeq.  oNZAAANBAAZe9.  ovbAAAbbAAS<,   ovbAAAbbAAA<,   ozVAAAxCAASf>X  ozVAAAVCAAAf>X  %yiBBuyrrrrr%   %yiBBuyrrrrr%  ",
" .7eS2meemfS6&.  .5eS2Vexm2S6&   OuuS2miMm2Z75.  ouuS2miim2S74.  oNZS2mNNm2Se9.  oNZS2mNNm2Seq.  #vbS2mbbm2D<,   ovbD2Vbbm2D<,   XzVSfmVVm2Df>X  XzVS2mVCmfSfsX  *yyuuu8trrrr*   *yyuuu8trrrr*  ",
" .5qf#22&2#2$%   .5q2@2==2#2$%   oyuF#2002#274.  oui2#2002@274.  oNNmO2mm1#2qq.  oNZmO2mx1#2qq.  #vbFO2vv2#2<,o  ovbf#2cn2#2<,o  .dVfO2zz>@fss.  .zVf#1dd2Ofs>.  *ryyyy8trtrt*.  *yyyyy*trtrt*. ",
" .5q&@@$$@#O$&   .5q&##$$@#O$%.  ouu=@&66&#$74.  oyu=@@89O#$74.  ONZ0#@ee@@&q9.  ONZ0#@eq@#&qq   ovb<@:c<@@#<,o X#vb1##c<##,,,   XzC2@@ss@#:ssX  XdC2@@fs@@:s>   *rrrrr*rr#%8*   *rrrrtO*r%#8*  ",
" .7q5$$33$$$$%   .5q5$$33$$3$&   oyuy89996*574.  Oyuy889964675.  #NZM00ww06qqq.  #NZM00Mwq6qq9.  ovbvc<cc,,<<,   ,vbv<ccc<,<<,   .dVz>sdd::ss>   .dVz>>zz>:sssX  %rrrrr*tr#O**.  %rrrr*oOt%o**. ",
" .5q75533333$&.  .5q75533333$&.  ouuuyy9999975.  Oyuuyy9999975.  #NZNwMMwwwwq9.  #NZNwwMwwwwqq.  ovbvvvvcc<<<,   ovbvvvvc<<<<,o  XzVCzzdzssss>.  XzVxdzzzssss>X  o8rrrr*trt**O   o8rrr%  tt**O  ",
" .5q75533333$%.  .5q755333333%   oyuuyy9999773.  ouuyyy9999674   #NZNMMMwwwwqqO  #NZNMMMwwwwe9.  ovbvvvccc<<,,o  ovbvvvvcc<<<,   .dVCzddzssss>X  odVxdzzzssss>X   %trrr*tt8**.    %trto  %8**.  ",
" .5q65533333$&   .5q755$$333$%   oyuyyy9999974.  oyuuyy6699974   #NZMMMMwwwqqq.  oNZMMM00wwwq7.  ovbvvvvcc<<<,   ovbvvv<<c<<<,o  ozVzddzdssss>X  .zVxzzs>ssss>X    =trr***8*.      =t*   O**O   ",
" .56.O5333O.&%.   Oq75$  $33$O   OytO%y999%.34.   =yyy8O.6997O   #Nm@&wMww&O69.   2NNM0.O6wwq&   ovl#,cvc<#X,,    ,bvvco ,<<,o   ozf+@dzds+X:>X   @VCz>.X:sss#      O%*%**O.        OO    Oo    ",
" .$.  O33O   O     &5$    $$O    o8O  %99%  .$.    =y8O  .67O    @0o X&Mw&X X&.    2M0. X.0q&    o<o  ,cc#   ,     ,v<o  o,<#    .>o. :zd@  X:.    :xs..  :s+         .                         ",
"       OO           O.    ..      .   .OO           %O    .O      X   X&&X          @.  X .&           ##           #o    oo           +@           @X    Xo                                    ",
"     .&&&&.X         .&&&&X.         O****.          O88**O          O2002O          O2002O          o1111.          o111@o          o>>2>X          o>2>>.                                     ",
"   o2eq6643O.      o2eq6653O       o0iuyy99$.      o2iuy999%.      .0NBNMwq&.      .0NBNMwq&.      o2nbvcc<#       o2nbvvc<#       o2VVxzfs@.      o2VVxzf>:        .O*=*%.          O*=*%.     ",
"  .zSM633333$     .zZM733333$     .mABu999994     omABy999993     .mZNMMwwww6X    .mZNMMwwww6X    omSDnccc<<,      mADvvc<<<,     .mASxzzsss:     .mASxzdsss:      %tyyrrr8%       %tyyyrr8%    ",
"  %MZM743444$.    %MZe633444$.    %BZBy999997O    =BABy999997O    &ZZNMMwwwwq&    &ZZNMMwwwwq&    ,VSbvcccc<,o    ,CSbvcccc<,o    @SAVzzzfsss+    :SAVzzzfsss+    %yii8rrrrt=     %yii8rrrrt=   ",
"  4wNZN66NZ0$&    4wNZN66NZ0$%    tBBAB9qBZM7$   otBBAB99BZi73   .mZZAZMMZZNq6   .mZZAZMMZZNq6X  ovbSSDvcDSm<,    cbSADvvDSb<,    fVSAVzzVSCs:    fVSSVxzVSCs:   otiAm 8rrrrtO    tBAF 8rrrrtO  ",
" .5emfSe02VZ&%.  .5emfSe0fmZ6%   OyimFSie2mZ75.  Oyum2Aie2mZ74.  oNZm2SNM2CZeq.  oNZm2SNM2CZe9.  ovbmfSbn2mS<,   ovbmfSnn2mS<,   ozVm2ZVx2VSs>X  .zVm2SVC2VSf>X  %yiBN*rrrrrr%   o*iSB8rrrrrr%  ",
" .5q2#De2o2S6&   .5q2#De&@fS=&.  Oyu2#Di0#2S75.  oyu2@DM0@2A74.  oNZ2#SZm@2Ae9.  oNZ2#SZm@2Aeq.  ovb2#Dbn#2S<,o  ovb1#Dbc@2S<,   XdV2@VVd#fSf>X  odC>@SVf@fSfs.  *uuuuuyrrrrr*.    o=*yrrrrrr*. ",
" .5qFDS6&mSm$%   .7qFDS2&CSm$&.  ouuFDS08mSm74.  oyuFDS08mSm75.  #NNmVSm0mSmqq.  #NNmVSm0mSme9.  ovbFDSnvmSm<,   ovbmDSnnmSm<,o  XdCmVZzdmSmssX  XzCmVSzfmSms>X  %*8888**rrrt*        o%*rrrt*  ",
" .7q=2&$$@2&$%   .5q=2&$$&2&$&.  Oyu82=99==&74.  oyu82=96=2$74.  oNZ022ee22&qq.  oNZ022eq&26eq.  ovb<21c<12#,,  o#vb121c<@2#,,   XzC22:df:2:ssX  ozC22:df&2:s>X  =tttttttrrr8*.      o=*trrr8*. ",
" .5q7$334$$$$&   .5q5$333$O$$%   oyuy899986575.  oyuy899986575.  #NZM0ewwq6qq9.  #NZM0ewwq6qe6.  ovbvcccc<,<<,o  ,vbv<ccc<,<<,o  odVx>sdd>:ss>   .zVxs>zd>:ss>X  %rrrrrtrrrt**.   o%8trrrrrt**. ",
" .5q75533333$&   .5q75533333$%   oyuyyy9999974.  oyuuyy9999975.  #NZNMMMwwwwe9.  #NZNMMMwwwwe9.  #vbvvvvcc<<<,o  ovbvvvccc<<<,   .zVCzzddssss>X  .dVxzzzzsssssX  o8rrrrrrr88*O   .*rrrrrrr88*O  ",
" .5q655333333%   .5q755333333%.  Oyuuyy9999974.  ouuuyy9999773.  #NZMwMMwwwwqq.  #NZMwMMwwwwqq.  #vbvvvccc<<<,   ovbvvvvcc<<<,   XzVxzzzzssss>.  XzVxzzzzssss>    %trrrrrt***     %trrrrrt***   ",
" .5q5553333$$&.  .5q555$$333$&   Oyuyyy9999673.  .yuuyy6699973.  #NZMMMMwwwqq9.  #NZNMMqqwwqe6.  ovbvvvvcc<<<,   ovbvvvc<c<<<,   odVzdzzdss>ss   XdVCzzs>ssss>X    =trrt8***O      =trrt8***O   ",
" .56.O4333O.%%    &q75$  $33$.   outO%y999%.35.   =yuy8..6997O   #Nm@&MMMe&.6q.   &NNM0..0wwq&   ovlo,ccc<#o,,o   ,nvvco <<<,o   odf+@dzds+X:>X   @Vxz>X.:sss+      o%****%.        O*****%.    ",
" .$.  O33O  .O.    &5$.   $$O    o*#  %99&  .$.    %y8.  .46O    #0#  &Mw&  X=.    2M0.  .6q&    o<o  ,cc#   #     1v<o   ,<#    .>o. @zd@   :X    :z>.  X:s@          o.              o.       ",
"  .    OO           O.     .      o    OO           %O    .O      X    @&    .      @o   XO@     Xo    #o           #o    oo           +@           @.    .+                                    ",
"     .&&&@.          .&&&@.          O**8*O          O*8**O          O2022.          o202=O         .o,111o          o111@o          o>2>>.          o:22>o                                     ",
"   O2eq6443O.      o2eq6443O.      o2iuy999%.      o2iuy999%.      o2NNMMwq6.      o0NZMMwq6o      o2nbncc<,       o2bbvvc<,       o2VCxzf>:X      o2VVxzf>@X        %*%%%o          o    .     ",
"  .zZN743333$      zZN743333$     .mABu999993      mABu999993     .mZZMMwwww6     o0ZZMMwwww6X     mSDvcc<<<,      mSDvvc<<<,     .mASxzzsss:.    .mASxzdsss:      Otyy*tr8%       %t*   o*%    ",
"  OMZe543443$.    &MZe5333$3$.    =BABy999997O    %BAiy999997O    =NZNMMwwwwe&   X=ZZMMMwwwwq&    ,VSbvvcc<<<o    ,CSbvvcc<<,o    @SAVzzdssss+    :SAVzzzssss+    %yBiu8trrt=     %yBio  %rt=   ",
"  4wM=2462@0$&    4wM=2462=0$&   orBN=2990=07$   otBN=0990=073   XmZN20MM0=ee6X  .mZV20MM0=ee6    cCm11vc21F<,    vCC11vv2@c<,    fVV>2zz>:fs:    fVV22zzs:ds:    8BABu*trrrtO    tiAS=  8rrtO  ",
" .7eV#2e02@m6%   .7eV#2e0f@m$%.  ouiN#2iM2@m75.  oyuD#2iM2@V74.  oNZV#2NNf@Ve9.  ONZV@2NN2@Veq.  ovbV#Fnb2#m<,   ovbD#2nb2@m<,   XzVV@2CC2@Vf>X  ozVV@2CC2@mfsX  %yiFiu8trrrr%   OyiFB* otrrr=  ",
" .5eSSSx0ASS$%.  .5eSSSx0ADS6%   oyuSSAiiSSZ75.  ouuSSAiiSSZ75.  #NZASSNNSDSe9.  #NZADSZNSSZe9.  #vbASSbbSDS<,   ovbSDSbbASS<,o  .zVADSVVSSSf>X  XzVADSVVSSSf>X  *y8o8u8trrrr*.  *y8 8yo=rrrr*o ",
" .7qmAS66SAm$&   .7qmAS66SAm$&.  oyuNAS00SAm55.  OyuVAS00SAm55.  oNZmASMmSAmeq.  oNNVASemSAmeq.  #vbmASvnSAm<,o  ovbVASnnSAm<,   .zVmAZzzSAmss   .zCVASzzSAms>.  *rr8ry*trrrt*.  =yr8rr%*rrrt*o ",
" .5q=2&$$&2&$%.  .5q*2&$$@2&$%.  ouu82=96=2$73.  Oyu82=96=2&73.  oNZ022ee=26q6.  oNZ022eq22=qq.  ovbc21c<12@,,   #vb121c<12#<,o  XzC22:df:1:ss.  .dC22:ff:2:s>   *rrrrr*trrt8*   *rrrrr*trrr8*. ",
" .5q6$333$O$$&.  .5q6$333$O$3&   oyuy989996675.  ouuy989996675.  oNZM0qMwq6qqq.  oNZM0ewwq6qe9.  ovbvcccc<,,<,o  ,vbv<ccc<,<<,   .dVx>sdz>:ss>X  odVx>>zz>:>s>X  %rrrrrrtrrt**   %rrrrrrrrrt**  ",
" .5q75533333$%   .5q55533333$%   oyuyyy9999973.  oyuyyy9999974.  #NZNwMMwwwwqq.  #NZNMMMwwwwq9.  ovbvvvccc<<<,   #vbvvvvc<<<<,o  XzVCzzdzssss>   ozVxdzzzssss>X  o8rrrrrrrt88O   .8rrrrrrr8**%  ",
" .7q75533333$%.  .7q75533333$%.  ouuyyy9999674.  oyuuyy9999774.  #NZNMwMMwwwq9.  #NZMMMMwwwwqq.  ovbvvvccc<<<,   ovbvvvvcc<<<,   .dVxzzzzssss>X  XdVxzzzzsssssX   %trrrrrt***.    %trrrrrt8**.  ",
" .5q65533333$%.  .5q755$$333$%   ouuyyy9999673.  oyuyyy6699953.  #NZNwMMwwwqe9   oNZMMM00wwwe6o  ovbvvvvcc<<<,   ovbvvv<<c<<<,o  ozVzdddzss>s>X  .zVxzzs>ssss>X   .=trrt88**.      =trrt8***O   ",
" .56OO5333O.&&    Oq75$  $33$O   Oyto%y999%.35.   =uuy8..6995O   #Nx@&MMwq&O6q.   2NNM0..6wwq&   ovl#,cvc<#o,,o   ,bvvco ,<<,o   ozf+:dzz>+X:>X   @VCz>.X:sss#      O%****O.        O%****O     ",
" .$.  O3$O   O.    &5$    $3O    o8o  %99$  .$     =y8.  .66&    #0O  &Mw&  .*.    2M0o  .6q&    o<o  ,cc#   #     ,v<o  o,<#    .>o  @dd@  X:.    :x>O.  :s+                           .       ",
"       OO           O      .      o    %%           %o    .O      o   X:&X  X      .@O    X&           ##           #o    oo           @@           @X    Xo          oooo            oooo      ",
"                                                                                                                                                                    X,llll,X        o,llll,X    ",
"     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ,lkkkjaaa#      ,lkdkjjaa,   ",
"   Xpghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg-X      XpghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgpX      XpghhhhgpX      XpghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgpX     #lkdkjaajaa+    :lkkfjajaaa#  ",
"  Xggp-----------------------------------;pgg+    Xggp------------------------------------pggX    Xggp----pggX    Xghp;-----------------------------------pggX   X<kbkdjjajaa<X XX<kbkkjaajaa<  ",
"  -g+X;----------------------------------;X+gp    -g+X;-------------------------------pp-;X+gp    ph+X;--;X+gp    pg+X;p---------------------------------;X+gp   ,kCCCbjjzCCla#  ,lCVVCjjzCCja# ",
" XgpXghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg+pgX  XgpXghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgXpgX  XgpXghhhhgXpgX  XgpXghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgXpgX  ,bVmzVbbVmVCa, X,lVmzVbbDmVVa, ",
" Xh-;h+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+h;-hX  Xh-;h+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+h;-hX  Xh-;h+XX+h;-hX  Xh-;h+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+h;-hX  ,bV@omCCm.@Vl,  ,bV@ozVCm @Dl, ",
" Xh--hX                                  Xh;-hX  Xh--hX                                  Xh--hX  Xh--hX  Xh--hX  Xh-;hX                                  Xh--hX  ,lV2:mmxm@2Vl, .,lD2@mxdC@2V1, ",
" Xh--hX                                  Xh--hX  Xh--hX                                  Xh--hX  Xh--hX  Xh--hX  Xh--hX                                  Xh--hX  ,kdVVmsamCCfp,  ,kzVVmssmVCfp, ",
" Xh--hX                                  Xh--hX  Xh--hX     XXXXXXXX       XXXXXXXXX     Xh--hX  Xh--hX  Xh--hX  Xh-;h+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+h;-hX  1kf>ssja:s:pa, .,kf2>saa->:pa, ",
" Xh--hX                                  Xh--hX  Xh--hX   +phhhhhhhhp+    +pghhhhhhhp+   Xh--hX  Xh--hX  Xh--hX  XgpXghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgXpgX  ,lCkjksaaappa,  ,kblkkjjaaaaa, ",
" Xh--hX                                  Xh--hX  Xh--hX   php-p---pphp    php-----pphp   Xh--hX  Xh--hX  Xh--hX   pg+X;----------------------------------;X+g-   ,kbdkkjjajapa, .1kbkkfjjajapp, ",
" Xh--hX                                  Xh--hX  Xh--hX  Xgp+ppp-p-+pgX  Xgp+pp-p--+pgX  Xh--hX  Xh--hX  Xh--hX   Xggp------------------------------------pggX   ,kbkkksaajaaa,  ,kblkkkajjaaa, ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh-phhhhhh--hX  Xh-phhhhhhp-hX  Xh--hX  Xh--hX  Xh--hX    XpghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgpX    ,kb<<kjjj<,aa,   <bkkl#+aaaa,X ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh-ph+XX+hp-hX  Xh-ph+XX+h--hX  Xh--hX  Xh--hX  Xh--hX      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      <l, oljj-o #a,   Xlll, X+aa,o  ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh--hX  Xhp-hX  Xh--hX  Xh--hX  Xh--hX  Xh--hX  Xh--hX                                                  ##   +<<o   ,+    X1@XooX,,o   ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh-phX  Xhp-hX  Xh--hX  Xhp-hX  Xh--hX  Xh--hX  Xh--hX                                                     o1nDDb<#        o1nbDb<#    ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh-ph+XX+h--hX  Xh--h+XX+hp-hX  Xh--hX  Xh--hX  Xh--hX      XXXXXX                                        ,bSAAAAAb,      ,bSAAAAAb,   ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh--hhhhhh;-hX  Xhp;hhhhhhp-hX  Xh--hX  Xh--hX  Xh--hX    Xpghhhhgp+                                     ,DAAAAAAAAD#    ,DAAAAAAAAD#  ",
" Xh--hX                                  Xh--hX  Xh--hX  Xgp+-p-pp;XpgX  XhpX;p-p-p+pgX  Xh--hX  Xh--hX  Xh--hX   Xghp;---pggX                                    lAAAAAAAAAAn    nAAAAAAAAAAn  ",
" Xh--hX                                  Xh--hX  Xh--hX   phpp----pphp    php------php   Xh--hX  Xh--hX  Xh--hX   pg+X;p-;X+g-                                   ,DAASSAASSSAD, X,DAAASAASASAD, ",
" Xh--hX                                  Xh--hX  Xh--hX   +phhhhhhhhp+    +pghhhhhhhp+   Xh--hX  Xh--hX  Xh--hX  XgpXghhhhgXpgX                                  <SDmmVSSVFCDS1  <SSmmVSSVzmDS1 ",
" Xh--hX                                  Xh--hX  Xh--hX     XXXXXXXX        XXXXXXXX     Xh--hX  Xh--hX  Xh--hX  Xh-;h+XX+h;-hX                                  <DD@ozAAmo@DD1  1AD@ozAAFo:DA1 ",
" Xh--hX                                  Xh--hX  Xh--hX                                  Xh--hX  Xh--hX  Xh--hX  Xh-;hX  Xh--hX                                  1DV2@mSSm@2VV<  <SD2@mSAm@2DS< ",
" Xh--hX                                  Xh--hX  Xh--hX                                  Xh--hX  Xh--hX  Xh--hX  Xh--hX  Xh;-hX                                  <SVVVmSSmVVCS<  <SmVVmSSVVVmS< ",
" Xh--hX                                  Xh--hX  Xh--hX    XXXXXXXXX        XXXXXXXXX    Xh--hX  Xh--hX  Xh--hX  Xh-;h+XX+h;-hX                                  1AAVVNAADVmSA<  1ADmVDAASSSSA< ",
" Xh--hX                                  Xh--hX  Xh--hX   +pghhhhhhgp+    +pghhhhhhgp+   Xh--hX  Xh--hX  Xh--hX  XgpXghhhhgXpgX                                  <AAAAAAAAAAAA<  <AAAAAAAAAAAA< ",
" Xh--hX                                  Xh--hX  Xh--hX   php------php   Xphp------php   Xh--hX  Xh--hX  Xh--hX   pg+X;-p;X+gp                                   <AAAAAAAAAAAA1  <AAAAAAAAAAAA1 ",
" Xh--hX                                  Xh--hX  Xh--hX  Xgp+ppp--;XphX  XgpX;p---p+phX  Xh--hX  Xh--hX  Xh--hX   Xggp----pggX                                   1AAAAAAAAAAAA1  1SAAAADSAAAAA, ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh-phhhhhh;-hX  Xh-;hhhhhh-phX  Xh--hX  Xh--hX  Xh--hX    XpghhhhgpX                                    <AD<nAAAAn1DA<  oFAAAD@,DAAAno ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh--h+XX+h--hX  Xh--h+XX+h--hX  Xh--hX  Xh--hX  Xh--hX      XXXXXX                                      <b1  nAAn  ,D<    nAD,  ,DAn   ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh-phX  Xhp-hX  XhpphX  Xhp-hX  Xh--hX  Xh--hX  Xh--hX                                                  #,    nn    ,#    oc1    1F    ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh--hX  Xh-phX  Xh-phX  Xh-phX  Xh--hX  Xh--hX  Xh--hX                      o ooo                                          X X   XX    ",
" Xh--hX                                  Xh--hX  Xh--hX  Xh--h+XX+hp-hX  Xh--h+XX+hp-hX  Xh--hX  Xh--hX  Xh--hX                     o@=12@@o.                                                   ",
" Xh--hX                                  Xh--hX  Xh--hX  Xhp-hhhhhhp-hX  Xhp-hhhhhhp-hX  Xh--hX  Xh--hX  Xh--hX                    #12FmmF22#.                                        .X        ",
" Xh--hX                                  Xh--hX  Xh--hX  Xhp+ppp-pp+pgX  Xhp+p---pp+pgX  Xh--hX  Xh--hX  Xh--hX      oO%%o        #20mmiimm21#                     XooX  XoX      X+::+X X#XX   ",
" Xh--hX                                  Xh--hX  Xh--hX   php------php    php------php   Xh--hX  Xh--hX  Xh--hX     .*rrrt*.     o@2miiiiiimF#o                   :fCmd;adCm1X    :bVCbp:dCCsX  ",
" Xh--hX                                  Xh--hX  Xh--hX   +pghhhhhhgp+    +pghhhhhhgp+   Xh--hX  Xh--hX  Xh--hX     *yuuuuy*     o2FiiBBBBiiF2#       .%O        XlDmmDbbVmmm:X   sVmmVbbVmmC:  ",
" Xh--hX                                  Xh--hX  Xh--hX     XXXXXXXX       XXXXXXXXX     Xh--hX  Xh--hX  Xh--hX    .tuuuuuu8O   o#2FiBBABBBiF2#      o8yr%       +fV@oFCCm @V:X  XfV1 FCCm @Vs  ",
" Xh--hX                                  Xh--hX  Xh--hX                                  Xh--hX  Xh--hX  Xh--hX    %ruuuuuur%   o#FiiBAAABBii2#o     %yuu8       +fD2@Cmmm:2V:X  +fV2@mxmm:2V:X ",
" Xh-;hX                                  Xh--hX  Xh-;hX                                  Xh--hX  Xh-;hX  Xh--hX    %yuuuuuur%    @2miBBAABBiF2#      Oruu*o      X:fDVmsamVVf+    :fVVm::mVVf+X ",
" Xh-;h+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+h;-hX  Xh-;h+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+h;-hX  Xh-;h+XX+h;-hX    OruuuuuutO    #20iBBBBBii02o       %8*o        +>>>:++:::+o    X:>1@XX:::+X  ",
" Xgp+ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgXpgX  Xgp+ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgXpgX  Xgp+ghhhhgXpgX     *yuuuuy*.    o@2iuBBBBii2@.                    ++++  X+Xo      o+XX  XX   o ",
"  pg+X;----------------------------------;X+gp    pg+X;----------------------------------;X+hp    pg+X;--;X+g-      o*tryr*o      #2F0iiiy022#                                                  ",
"  +ggp------------------------------------phgX    +ggp------------------------------------pggX    +ggp----pggX        O%%O        .#222FFF21#                                                   ",
"   X-ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgpX      X-ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgpX      X-ghhhhgpX                      o#@=22=#o.                                                   ",
"     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXX                          oo##oo                                                     ",
"                                                                                                                                       .                                                        "
};
